# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7644d11f8d10ea90ae248d16351a9cca0b9334f8a9babdf5742ca0d497cca7c4465f63c2c2871eee43f051bb86ec706e1e9810e844f6ff38231fd411b9404989

test:
  secret_key_base: 764975b8e1e0ad26f81ac8bbfa66fb3a9f1ad8f128a1b88e3ef810bab1ce639b142f883e7839d25d49650deb72b809aefbb01e5b134e431fac946ce719f3db05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
